const certificates = {
  1: {es: 'Buenas Prácticas para Escritura de Código', us: 'Good Practices for Code Writing'},
  2: {es: 'Desarrollo Web Online', us: 'Online Web Development'},
  3: {es: 'Introducción a PHP', us: 'PHP Introduction'},
  4: {es: 'jQuery a JavaScript', us: 'jQuery to JavaScript'},
  5: {es: 'Marca Personal', us: 'Personal brand'},
  6: {es: 'Next.js', us: 'Next.js'},
  7: {es: 'Programación Funcional en JavaScript', us: 'Functional Programming in JavaScript'},
  8: {es: 'React Avanzado', us: 'Advanced React'},
  9: {es: 'React Router', us: 'React Router'},
  10: {es: 'Redux', us: 'Redux'},
  11: {es: 'Diseño Adaptativa', us: 'Responsive Design'},
  12: {es: 'Render en el servidor con Express', us: 'Server Side Render with Express'},
  13: {es: 'Programación Básica', us: 'Basic Programming'},
  14: {es: 'Curso Práctico de React JS', us: 'React JS Practical Course'},
  15: {es: 'Git y GitHub', us: 'Git and GitHub'},
  16: {es: 'Fundamentos de Ingeniería de Software', us: 'Fundamentals of Software Engineering'},
  17: {es: 'Fundamentos de JavaScript', es: 'Fundamentals of Javascript'},
  18: {es: 'Vue.js', us: 'Vue.js'},
  19: {es: 'JavaScript y jQuery', us: 'JavaScript and jQuery'}, 
  20: {es: 'React.js', us: 'React.js'},
  21: {es: 'Redux', us: 'Redux'},
  22: {es: 'Posicionamiento en buscadores', us: 'Search Engine ptimization'},
  23: {es: 'WebpackJs', us: 'WebpackJs'},
  24: {es: 'Marketing Voz a Voz', us: 'Voice to Voice Marketing'},
}

export default certificates;